apiVersion: v1
kind: Service
metadata:
  name: tesco-checklist
spec:
  type: NodePort
  selector:
    app: tesco-checklist
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can pick any free port between 30000–32767
