apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesco-checklist
spec:
  template:
    spec:
      containers:
        - name: tesco-checklist
          image: mhefner1983/tesco-checklist:arm64  # tag it differently for dev
          imagePullPolicy: Always
